[package]
name = "axum_movies"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.1"
axum-extra = { version = "0.4.2", features = ["erased-json"] }
serde = { version = "1.0.150", features = ["derive"] }
serde_derive = "1.0.150"
serde_json = "1.0.89"
tokio = { version = "1.23.0", features = ["full"] }
tower-http = { version = "0.3.5", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
