version: '3'

services:
  database:
    image: 'postgres:14.1'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: axum_quasar 
  app:
    image: 'axum-quasar'
    ports:
      - 3000:3000 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database/axum_quasar