version: '3'

services:
  database:
    image: 'postgres:14.1'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: axum_quasar 
  app:
    image: 'registry.fly.io/axum-quasar'
    ports:
      - 8080:8080 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database/axum_quasar