version: '3'

services:
  database:
    image: 'postgres:14.1'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: axum 
      POSTGRES_PASSWORD: axum 
      POSTGRES_DB: axum_movies 
  app:
    image: 'repo/axum-quasar'
    ports:
      - 3000:3000 
    environment:
      - DATABASE_URL=postgres://axum:axum@database/axum_movies