[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build-backend]
command = "cargo"
args = ["build", "--release"]

[tasks.build-frontend]
command = "yarn"
args = ["--cwd", "frontend", "quasar", "build"]

[tasks.dev-server]
command = "cargo"
args = ["run"]
dependencies = ["build-frontend"]

[tasks.build-docker]
command = "docker"
args = ["build", "-t", "registry.fly.io/axum-quasar:latest", "."]

[tasks.start-proxy]
command = "flyctl"
args = ["proxy", "6542:5432", "-a axum-quasar-db"]
